namespaces:
  default:
    pod:
      labels:
        Team: devops
        Env: prod
        Project: k8s
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Team=devops,Env=prod,Project=k8s"
    persistentVolumeClaim:
      annotations:
        ebs-tagger.kubernetes.io/ebs-additional-resource-tags: "Team=devops,Env=prod,Project=k8s"
  other_namespace:
    pod:
      annotations:
        annotation_key: value
      labels:
        label_key: value
  "*":
    pod:
      annotations:
        default_annotation: value
      labels:
        default_label: value