resources:
  - service.yaml
  - rbac.yaml
  - webhook.yaml
  - deployment.yaml

configMapGenerator:
- name: k8s-metadata-injector
  namespace: kube-system
  files:
    - conf/metadataconfig.yaml

generatorOptions:
  disableNameSuffixHash: false
