apiVersion: v1
kind: Service
metadata:
  name: k8s-metadata-injector
  namespace: kube-system
  labels:
    app: k8s-metadata-injector
spec:
  ports:
  - port: 443
    targetPort: 8080
    name: webhook
  selector:
    app: k8s-metadata-injector
